"""Idempotent synthetic data through canonical services; never copies client rows."""

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.app.audit.contracts import AuditEventCreate
from apps.api.app.audit.enums import AuditActorType, AuditResult
from apps.api.app.audit.service import AuditEventService
from apps.api.app.config import EnvironmentName, Settings
from apps.api.app.industries.models import Industry
from apps.api.app.industries.seed import IndustrySeeder
from apps.api.app.integrations.connection_service import (
    ANALYTICS_SCOPE,
    SEARCH_CONSOLE_SCOPE,
    GBPConnectionService,
)
from apps.api.app.integrations.models import IntegrationConnection
from apps.api.app.integrations.provider_seed import ProviderCatalogSeeder
from apps.api.app.locations.contracts import LocationCreate
from apps.api.app.locations.enums import LocationType
from apps.api.app.locations.service import LocationService
from apps.api.app.organizations.contracts import OrganizationCreate
from apps.api.app.organizations.enums import OrganizationType
from apps.api.app.organizations.service import OrganizationService
from apps.api.app.products.analytics.service import AnalyticsService
from apps.api.app.products.content.contracts import TargetCreate
from apps.api.app.products.content.models import PublishingTarget
from apps.api.app.products.content.service import ContentService
from apps.api.app.products.gbp.adapter import BUSINESS_MANAGE_SCOPE
from apps.api.app.products.seo.contracts import SearchPropertyCreate, WebsiteCreate
from apps.api.app.products.seo.service import SEOService
from apps.api.app.staging.provider_fixtures import (
    FixtureAnalyticsAdapter,
)

# Stable logical keys/values; UUIDs are generated by the canonical services once.
SHAPES = (
    ("hospitality", "restaurant", "healthy", 1),
    ("home-service", "home_services", "healthy", 1),
    ("multi-location", "restaurant", "healthy", 3),
    ("reconnect", "restaurant", "expired", 1),
    ("partial", "home_services", "partial", 1),
    ("unavailable", "restaurant", "unavailable", 1),
    ("rate-limited", "restaurant", "rate_limited", 1),
    ("missing-mapping", "restaurant", "missing_mapping", 1),
    ("publishing", "restaurant", "healthy", 1),
)


def require_seed_environment(settings: Settings) -> None:
    if (
        settings.environment is not EnvironmentName.STAGING
        or settings.google_provider_mode != "fixture"
    ):
        raise ValueError("Synthetic seed requires isolated staging with fixture providers")


async def seed_staging(session: AsyncSession, settings: Settings) -> dict[str, str]:
    require_seed_environment(settings)
    # Serialize this re-runnable packet; do not race unique service creates.
    await session.execute(text("SELECT pg_advisory_xact_lock(5052026)"))
    await IndustrySeeder().run(session)
    await ProviderCatalogSeeder().run(session)
    organizations = OrganizationService()
    locations = LocationService()
    seo = SEOService()
    connections = GBPConnectionService()
    ids: dict[str, str] = {}
    for key, industry_key, scenario, count in SHAPES:
        slug = f"staging-{key}"
        reference = f"fixture:{scenario}:{key}"
        organization = await organizations.repository.get_by_slug(session, slug)
        if organization is None:
            industry = await session.scalar(select(Industry).where(Industry.key == industry_key))
            assert industry is not None
            organization = await organizations.create(
                session,
                OrganizationCreate(
                    name=f"Synthetic {key}",
                    slug=slug,
                    organization_type=OrganizationType.TEST,
                    timezone="America/Los_Angeles",
                    default_currency="USD",
                    industry_id=industry.id,
                    external_reference=reference,
                ),
                correlation_id="staging-seed",
            )
        elif (
            organization.external_reference != reference
            or organization.organization_type is not OrganizationType.TEST
        ):
            raise ValueError("Synthetic seed refuses an existing non-fixture organization")
        ids[key] = str(organization.id)
        for number in range(1, count + 1):
            location_slug = f"site-{number}"
            if (
                await locations.repository.get_by_slug(session, organization.id, location_slug)
                is None
            ):
                service_area = industry_key == "home_services"
                await locations.create(
                    session,
                    organization.id,
                    LocationCreate(
                        name=f"Synthetic site {number}",
                        slug=location_slug,
                        location_type=LocationType.SERVICE_AREA
                        if service_area
                        else LocationType.PHYSICAL,
                        timezone="America/Los_Angeles",
                        country_code="US",
                        service_area_description="Synthetic service area" if service_area else None,
                        address_line_1=None if service_area else "1 Example Way",
                        city=None if service_area else "Example City",
                        region=None if service_area else "CA",
                        postal_code=None if service_area else "00000",
                        is_primary=number == 1,
                    ),
                    correlation_id="staging-seed",
                )
        websites = await seo.list_websites(session, organization.id)
        website = next((item for item in websites if item.key == "synthetic"), None)
        if website is None:
            website = await seo.create_website(
                session,
                organization.id,
                WebsiteCreate(
                    key="synthetic",
                    name="Synthetic website",
                    canonical_origin=f"https://{key}.invalid",
                ),
                actor_id=None,
                correlation_id="staging-seed",
            )
        provider = await connections.get_provider(session)
        connection = await connections.get_or_create_pending_connection(
            session, organization.id, provider
        )
        if connection.credential_reference is None and connection.status == "pending":
            connection.credential_reference = reference
            connection.external_account_reference = reference
            connection.status = "reconnect_required" if scenario == "expired" else "connected"
            connection.granted_capabilities = [
                BUSINESS_MANAGE_SCOPE,
                SEARCH_CONSOLE_SCOPE,
                ANALYTICS_SCOPE,
            ]
            await session.flush()
            await AuditEventService().record(
                session,
                AuditEventCreate(
                    event_type="integration.fixture.seeded",
                    action="integration.fixture.seeded",
                    actor_type=AuditActorType.SYSTEM,
                    result=AuditResult.SUCCEEDED,
                    organization_id=organization.id,
                    resource_type="integration_connection",
                    resource_id=connection.id,
                    correlation_id="staging-seed",
                    summary="Synthetic provider scenario configured; no live connection claimed.",
                    metadata={"scenario": scenario},
                ),
            )
        elif connection.credential_reference != reference:
            raise ValueError("Synthetic seed refuses a live provider connection")
        if scenario not in {"expired", "missing_mapping"}:
            properties = await seo.list_search_properties(session, organization.id, website.id)
            if not properties:
                await seo.create_search_property(
                    session,
                    organization.id,
                    website.id,
                    SearchPropertyCreate(
                        connection_id=connection.id,
                        external_property_id=f"sc-domain:{key}.invalid",
                        property_type="domain",
                    ),
                    actor_id=None,
                    correlation_id="staging-seed",
                )
            analytics = AnalyticsService(adapter=FixtureAnalyticsAdapter())
            from apps.api.app.products.analytics.models import AnalyticsProperty

            existing = await session.scalar(
                select(AnalyticsProperty).where(
                    AnalyticsProperty.organization_id == organization.id
                )
            )
            if existing is None:
                await analytics.map_property(
                    session,
                    settings,
                    organization.id,
                    external_property_id="properties/1001",
                    property_number="1001",
                    display_name="Synthetic analytics",
                    website_id=website.id,
                    actor_id=None,
                    correlation_id="staging-seed",
                )
        if key == "publishing" and settings.staging_github_repository:
            # An actual independently connected installation is an external prerequisite.
            github = await session.scalar(
                select(IntegrationConnection).where(
                    IntegrationConnection.organization_id == organization.id,
                    IntegrationConnection.external_account_reference
                    == f"installation:{settings.staging_github_installation_id}",
                    IntegrationConnection.status == "connected",
                )
            )
            target = await session.scalar(
                select(PublishingTarget).where(
                    PublishingTarget.organization_id == organization.id,
                    PublishingTarget.key == "staging-test",
                )
            )
            if github is not None and target is None:
                await ContentService().create_target(
                    session,
                    organization.id,
                    TargetCreate(
                        key="staging-test",
                        connection_id=github.id,
                        repository_id=settings.staging_github_repository,
                        base_branch=settings.staging_github_base_branch,
                        allowed_path_prefix=settings.staging_github_path_prefix,
                    ),
                    actor_id=None,
                    correlation_id="staging-seed",
                )
    return ids
